---
- hosts: myhosts 
  become: true 
  tasks: 

  - name: install apache2 and php support package on ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php package on rhel
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes 
    when: ansible_distribution == "AlmaLinux"
