---
- hosts: myhosts 
  become: true 
  tasks: 

  - name: install apache2 and php support packages
    package: #generic package manager in ansible to auto select the pkg_mgr for a distro.
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest 
      update_cache: yes

